### ISSUE TITLE
choose which trans namespaces to export

### ISSUE THREAD

**Issue by lsmith77** [GENL/matice#11]
### Expected behavior
 
only selected name spaces are exported to js to control the size of the javascript file

### Current behavior

all namespaces are exported

**Comment by GENL** [comment]
This can be useful if there are too many translations. I will add it in the next release.
It will be possible to specify in the config file a white list of folders or files to export. Likewise, it will be possible to define a blacklist of folders and files that should not be exported.

**Comment by lsmith77** [comment]
awesome thx

**Comment by GENL** [comment]
Now available in release [`1.1.5`](https://github.com/GENL/matice/releases/tag/1.1.5)
