### ISSUE TITLE
Laravel 8 - Vue3 Matice is not defined.

### ISSUE THREAD

**Issue by yakupguvenc** [GENL/matice#19]
Hello,

i am using laravel8 with vue3. 
I installed matice but i got this error "Matice is not defined" on app.js when i render my page.

my app code:
```
import {__, trans, setLocale, getLocale, transChoice, MaticeLocalizationConfig, locales} from "matice"


const el = document.getElementById('app');

createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(`./Pages/${name}`).default,
        }),
})
    .mixin({ methods: { route,
            $trans: trans,
            $_: _,
            $transChoice: transChoice,
            $setLocale(locale) {
                setLocale(locale);
                this.$forceUpdate() // Refresh the vue instance(The whole app in case of SPA) after the locale changes.
            },
            // The current locale
            $locale() {
                return getLocale()
            },
            // A listing of the available locales
            $locales() {
                return locales()
            }
    } })
    .use(InertiaPlugin)
    .mount(el);

InertiaProgress.init({ color: '#4B5563' });
```

**Comment by GENL** [comment]
Make sure you have included `@translations` before your js bundle.

**Comment by I3G-Carlos** [comment]
> 
> 
> Make sure you have included `@translations` before your js bundle.

He's using Inertia, he shouldn't be using a blade directive. It's the same issue as #18

**Comment by zorca** [comment]
> > Make sure you have included `@translations` before your js bundle.
> 
> He's using Inertia, he shouldn't be using a blade directive. It's the same issue as #18

Inertia is an unusual SPA, you can throw the Matice constant into it through a directive in the app.blade.php. Routes are added in the same way: `@routes`
