### ISSUE TITLE
Is there a way to remove comments?

### ISSUE THREAD

**Issue by hcancelik** [GENL/matice#21]
Hi,

Is there a way to remove the following comment being generated with this package?

```
<!-- Matice Laravel Translations generated -->
--
<!-- Used cached translations at: /home/forge/xxxx/xxx/xxxx/resources/assets/js/translations.js -->
```

**Comment by GENL** [comment]
Upgrade to the latest release, currently [1.1.6](https://github.com/GENL/matice/releases/tag/1.1.6). The path is no longer in the comments.
