### ISSUE TITLE
Unhandled Promise Rejection: Locale [nl_BE] does not exist in Safari

### ISSUE THREAD

**Issue by JanCusters** [GENL/matice#24]
Hi, thanks for the package. I'm using it with Laravel and Jetstream / Inertia. 
In Chrome everything works fine but when opening my project in Safari it wouldn't load because of the following error:

`Unhandled Promise Rejection: Locale [nl_US] does not exist.`

### Versions

- **Laravel**: 8.47.0
- **Matice**: 1.1.6

**Comment by GENL** [comment]
Please I need more information about the issue,

**Comment by JanCusters** [comment]
It looks like the problem occurs on all browsers with a composite locale like for example `en_US`, but not with `en`

**Comment by GENL** [comment]
Can you print the portions of the code where you define your locale? And also the function that throws the error?

**Comment by JanCusters** [comment]
Woops, the problem seemed to be on my side. Sorry for disturbing you.

**Comment by alessiovietri** [comment]
Hi @JanCusters , what was causing this error to you?
