### ISSUE TITLE
Translations not being generated

### ISSUE THREAD

**Issue by infospherebv** [GENL/matice#36]
### Expected behavior

We are using three languages (EN, DE AND NL). In the DE version there are special characters such as ä. For some reason it seems to work in some of the translation files, while in others it causes the @translations string in the app blade to become empty and causes the whole application to no longer render.

### Versions

- **Laravel**: 8.83.23
- **Matice**: 1.1

### Transalations
[Archief.zip](https://github.com/GENL/matice/files/9861136/Archief.zip)

### Contents of `Matice.translations`

???

**Comment by GENL** [comment]
Hi, thanks for opening this issue. I will test with your files and I will come back to you with more insight.

**Comment by infospherebv** [comment]
Hi, have you already had the chance to look into this? Thanks in advance!

**Comment by gildastema** [comment]
I @infospherebv are you use Jetstream ?

**Comment by infospherebv** [comment]
Yes we are using jetstreamMet vriendelijke groet,Erwin van den BergInfoSphere BVKastaanjelaan 4005616 LZ EindhovenTel: +31 (0)40 – 340 02 ***@***.***: 171.30815BTW: NL 8105.49.153.B01Op 10 nov. 2022 om 17:50 heeft Gildas Tema ***@***.***> het volgende geschreven:﻿
I @infospherebv are you use Jetstream ?

**Comment by gildastema** [comment]
The first thing I see is that there are keys in the DE file that do not exist in EN. Which can cause problems. And also please if you can send us the problem cases.

**Comment by infospherebv** [comment]
The strange this is that it fails if I change one normal character to a special (accented) character. But the same character is also in one of the other files and there it works (same language).Met vriendelijke groet,Erwin van den BergInfoSphere BVKastaanjelaan 4005616 LZ EindhovenTel: +31 (0)40 – 340 02 ***@***.***: 171.30815BTW: NL 8105.49.153.B01Op 10 nov. 2022 om 19:40 heeft Gildas Tema ***@***.***> het volgende geschreven:﻿
The first thing I see is that there are keys in the DE file that do not exist in EN. Which can cause problems. And also please if you can send us the problem cases.

**Comment by GENL** [comment]
Closing this for now as it could not be reproduced.
