### ISSUE TITLE
[question] New package version publish?

### ISSUE THREAD

**Issue by Celant** [GENL/matice#38]
Hey, thanks for all your work on this package!

With the PR to fix the release-it vulerabilities merged in, could we get a new package version published? I'd love to finally silence the screaming vulnerability alerts I'm getting :)

**Comment by vpuentem** [comment]
same here

**Comment by Coding-Kiwi** [comment]
yes please.. was just about to create an issue

**Comment by GENL** [comment]
Hey guys, Sorry for the wainting time. A new package version as indeed been released. 
Also related https://github.com/GENL/matice/issues/41

Thanks again!
