### ISSUE TITLE
Always add Fallback language

### ISSUE THREAD

**Issue by jeyemwey** [GENL/matice#39]
### Expected behavior
When using `@translations`, I want to get the translations of the _current_ user language and the fallback language, but not of all languages.

### Current behavior

`@translations` provides all languages which can be very large. `@translations("de")` only provides German but not the specified fallback language which can result in errors.

### Versions

- **Laravel**: 9.54.2
- **Matice**: 1.1.7

### Contents of `Matice.translations`
With `@translations`:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/2796271/227176959-f5d78671-f5dd-448d-ae85-025d3b55cf7f.png">

With `@translations("de")`:

<img width="199" alt="image" src="https://user-images.githubusercontent.com/2796271/227177188-2c9edf39-7cd7-46e8-bca2-1d47d3ce4eda.png">

---

Is there an easy way to fix this? Pushing all language data over the wire seems wasteful. Thank you for any help.

**Comment by GENL** [comment]
Just in case you didn't notice @jeyemwey, this issue has been fixed as part of the latest release v1.1.8. Thanks for the patience, I'm now maintaining this package again.

**Comment by jeyemwey** [comment]
Yes, thank you for bringing that on!
