### ISSUE TITLE
Publish latest release on npm

### ISSUE THREAD

**Issue by vpuentem** [GENL/matice#41]
Can you publish the latests releases on npm? 

Thanks in advance

**Comment by vpuentem** [comment]
Hi, any updates?

**Comment by GENL** [comment]
Hey Hey. Sorry for the infinite waiting time. I'm actively supporting the Repo again from now. 

The latest release is now published

**Comment by patrickomeara** [comment]
Fantastic news @GENL . Thanks ❤️
