### ISSUE TITLE
No named export in generated translations.js file

### ISSUE THREAD

**Issue by MitichPavel** [GENL/matice#43]
### Expected behavior

In readme.md has been added example of `matice_translation.js` generated by command `php artisan matice:generate`.
```
// matice_translations.js

const Matice = {
    locale: 'en',
    fallbackLocale: 'en',
    translations: {
      en: {
        auth: {
          failed: 'These credentials do not match our records.',
          throttle: 'Too many login attempts. Please try again in :seconds seconds.'
        }
      }
    }
};

export { Matice }; // expected named export
```
There is not named export in file `matice_translations.js` after generating.

### Current behavior

Now generated JS file looks like below
```
// matice_translations.js

const Matice = {
    locale: 'en',
    fallbackLocale: 'en',
    translations: {
      en: {
        auth: {
          failed: 'These credentials do not match our records.',
          throttle: 'Too many login attempts. Please try again in :seconds seconds.'
        }
      }
    }
};

```

### Versions

- **Laravel**: 10.26.2
- **Matice**: 1.1.4

### Possible solution

```

        $generatedTranslations = "
/*
|--------------------------------------------------------------------------
| Generated Laravel translations
|--------------------------------------------------------------------------
|
| This file is autogenerated and should not be modified.
| To load new translations run: php artisan matice:generate
|
*/\n\n" . $generatedTranslations . "\nexport { Matice };\n";
```
in file `matice/src/Commands/TranslationsGeneratorCommand.php` append `. "\nexport { Matice };\n"`;

**Comment by jordansitbon** [comment]
Or just add a config param `export_in_generated`

**Comment by GENL** [comment]
Just in cases you didn't notice @MitichPavel @jordansitbon, this issue has been fixed as part of the latest release v1.1.8. Sorry for the long delay, I'm now maintaining this package again.

**Comment by JapSeyz** [comment]
Would it be possible to make the export keyword optional?

Adding the export, makes it impossible to manually import the translations ala: `<script src="/translations.js?v={{ filemtime(public_path('translations.js')) }}"></script>`

as it fails with an error: `SyntaxError: Unexpected keyword 'export'`

**Comment by GENL** [comment]
@JapSeyz why don't you use the `@translations` directive instead?

**Comment by JapSeyz** [comment]
@GENL In the documentation, you suggest importing it manually when working with SPAs:
https://github.com/GENL/matice?tab=readme-ov-file#use-with-spa

![image](https://github.com/GENL/matice/assets/2234034/d4e54294-16a9-44a4-ad28-c7a5fb5e8881)

**Comment by GENL** [comment]
True! But looks like in your case you are able to call the blade directive directly.

**Comment by GENL** [comment]
I guess you generate the translations yourself using the command. Will a command option to omit the export statement solve the issue you're facing?

**Comment by JapSeyz** [comment]
I am working with an Inertia SPA. _Technically_ I can call the blade directive directly, but it seems odd to break something that was working.

I don't see how the readme-code would ever work, as export is not a native browser command.

> Will a command option to omit the export statement solve the issue you're facing

Yup

**Comment by GENL** [comment]
Version 1.1.9 released with the `--no-export` option added to the command. Thanks @JapSeyz for pointing out this limitation.
