### ISSUE TITLE
Blade directive markup

### ISSUE THREAD

**Issue by IamXytric** [GENL/matice#7]
### Expected behavior
```html
<!-- Matice Laravel Translations generated -->
<script>
  const Matice = {
    locale: "en",
    fallbackLocale: "en",
    translations: { ... }
  }
</script>
```
### Current behavior
```html
<!-- Matice Laravel Translations generated -->
<div id="matice-translations">
  <script type="text/javascript">
    const Matice = {
      locale: "en",
      fallbackLocale: "en",
      translations: { ... }
    }
  </script>
</div>
```

### Reasoning
- The div#matice-translations seems excessive and &lt;div&gt;s are not supported within the &lt;head&gt; forcing the directive into the &lt;body&gt;. Not that this is a big problem, but having the option to put it in &lt;head&gt; would be nice.

- This is just a very minor nuisance, but in HTML5 it is recommended to omit [type="text/javascript"] from &lt;script&gt;. Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

### Versions

- **Laravel**: 8.15.0
- **Matice**: 1.1.2

**Comment by GENL** [comment]
Hi!
Now possible with the release [1.1.3](https://github.com/GENL/matice/releases/tag/1.1.3) . Moved the `id` in the script tag directly.
